// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trns.Data;

namespace Trns.Data.Migrations
{
    [DbContext(typeof(TranslationContext))]
    partial class TranslationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Trns.Data.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlockedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("BlockedTime");

                    b.Property<string>("CheckedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CheckedTime");

                    b.Property<string>("Comment")
                        .HasMaxLength(500);

                    b.Property<string>("EditedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("EditedTime");

                    b.Property<string>("Edition")
                        .HasMaxLength(20);

                    b.Property<string>("Spanish");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("TransBy")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("TransDate");

                    b.Property<string>("TransKey")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
